---
title: "ABM/DTA Convergence Measures"
output: word_document
date: "September 12, 2016"
---



## iSAM Convergence Measures
## 

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=7}

oldw <- getOption("warn")
options(warn = -1)

library(dplyr)
library(readr)
library(ggplot2)
library(rmarkdown)
library(reshape2)

#######################
# INPUTS & PARAMETERS
#######################

# Set number of iterations (starting at 0)
numIters = 7


# Location of summary files
setwd("D:/OH_ABM_DTA/6_Integration/Runs/convergence_12sep2016")

#######################
# INPUTS & PARAMETERS
#######################


iters <- c(0:numIters)



# Pre-process iter -1
  currpSumm <- read_csv(paste("iter", "Neg1","_inconsistent_summ.csv",sep=""))
  datarows <- nrow(currpSumm)
  currpSumm[datarows+1,] <- colSums(currpSumm)
  currpSumm[datarows+1,"persType"] <- 0
  currpSumm[datarows+1,"dailyActivityPattern"] <- 0
  perSumm <- currpSumm %>%
    mutate(iteration  = -1,
           unstable   = NA,
           pcstressed = NA,
           pcunstable = 0,
           pcinconsistent = inconsistent/persons*100,
           persons_unstable = 0,
           trips_unstable = 0)  
  

for (itNum in iters) {
 
  if (itNum < numIters) {
  # Inconsistent Summary
      currpSumm <- read_csv(paste("iter", itNum,"_inconsistent_summ.csv",sep=""))
      
      # Add total row, with persType = 0 and dailyActivityPattern = 0
      datarows <- nrow(currpSumm)
      currpSumm[datarows+1,] <- colSums(currpSumm)
      currpSumm[datarows+1,"persType"] <- 0
      currpSumm[datarows+1,"dailyActivityPattern"] <- 0
      
      # Add iteration number column
      currpSumm <- currpSumm %>%
        mutate(iteration = itNum,
               pcinconsistent = inconsistent/persons*100)  
      
      perSummthisiter <- currpSumm

  
 # Stressed & Stability Summary
      currpSumm <- read_csv(paste("iter", itNum,"_stable_stressed_summ.csv",sep=""))
      
      datarows <- nrow(currpSumm)
      currpSumm[datarows+1,] <- colSums(currpSumm)
      currpSumm[datarows+1,"persType"] <- 0
      currpSumm[datarows+1,"dailyActivityPattern"] <- 0
      
      currpSumm <- currpSumm %>%
        mutate(iteration  = itNum,
               persons_unstable = persons,
               trips_unstable = trips,
               pcstressed = stressed/persons*100,
               pcunstable = unstable/persons*100) 
      
      currpSumm_s <- currpSumm %>%
        select(persType, dailyActivityPattern, iteration, persons_unstable, trips_unstable,
               pcunstable, unstable, stressed, pcstressed)
      
      fullSummthisiter <- left_join(perSummthisiter, currpSumm_s, by = c("persType", "dailyActivityPattern", "iteration"))
      
      #j <- left_join(perSumm, currpSumm, by=c("persType", "dailyActivityPattern"))
      #j$pcunstab

            
     # Append current iter to summary file
      perSumm <- bind_rows(perSumm, fullSummthisiter)
      
  }
  
  if (itNum == 7){
    currpSumm <- read_csv(paste("iter", itNum,"_stable_stressed_summ.csv",sep=""))
      
    datarows <- nrow(currpSumm)
    currpSumm[datarows+1,] <- colSums(currpSumm)
    currpSumm[datarows+1,"persType"] <- 0
    currpSumm[datarows+1,"dailyActivityPattern"] <- 0
      
    currpSumm <- currpSumm %>%
      mutate(iteration  = itNum,
             persons_unstable = persons,
             trips_unstable = trips,
             pcunstable = unstable/persons*100,
             inconsistent = NA,
             pcstressed = stressed/persons*100,
             pcinconsistent = NA) 
    
    perSumm <- bind_rows(perSumm, currpSumm)
    
  }
  
}


######################
# Plots
######################

perSumm$persTypef <- factor(perSumm$persType, levels=c(0:8), 
                            labels=c("All Person Types","FT Worker", "PT Worker","University Student",
                                     "Non-Worker", "Retiree", "Driving Age Student",
                                     "Pre-Driving Age Student", "Pre-school Child"))
perSumm$dapf <- factor(perSumm$dailyActivityPattern, levels=c(0:2), 
                            labels=c("All","Mandatory", "Non-Mandatory"))
perSumm$ptypeDAP <- with(perSumm,interaction(persType, dailyActivityPattern, drop=TRUE))
perSumm$ptypeDAPf <- with(perSumm,interaction(persTypef, dapf, drop=TRUE))


```

### 8 Person Types, for 3 Different Stress Measures

```{r, echo=FALSE, message=FALSE, fig.width=10, fig.height=7}
# Ptype by Measures (#)
#-----------------------------------

nototal <- perSumm[perSumm$persType>0,]

nototal <- nototal %>%
  mutate(totTravelTime = persons * avgTravelTime,
         totActTime = persons * avgActTime)

nototal <- nototal %>%
  group_by(persType, iteration) %>%
  summarise(trips = sum(trips),
            persons = sum(persons),
            trips_unstable = sum(trips_unstable),
            persons_unstable = sum(persons_unstable),
            stressed = sum(stressed),
            unstable = sum(unstable),
            inconsistent = sum(inconsistent),
            numNegDurActivities = sum(numNegDurActivities),
            totTravelTime = sum(totTravelTime),
            totActTime = sum(totActTime)
            )%>%
  ungroup()

nototal <- nototal %>%
  mutate(avgActTime = totActTime / persons,
         avgTravelTime = totTravelTime / persons,
           pcstressed = stressed/persons*100,
           pcunstable = unstable/persons_unstable*100,
           pcinconsistent = inconsistent/persons*100)

nototal$persTypef <- factor(nototal$persType, levels=c(1:8), 
                            labels=c("FT Worker", "PT Worker","University Student",
                                     "Non-Worker", "Retiree", "Driving Age Student",
                                     "Pre-Driving Age Student", "Pre-school Child"))
# nototal$dapf <- factor(nototal$dailyActivityPattern, levels=c(1:2), 
#                        labels=c("Mandatory", "Non-Mandatory"))
# nototal$ptypeDAP <- with(nototal,interaction(persType, dailyActivityPattern, drop=TRUE))
# nototal$ptypeDAPf <- with(nototal,interaction(persTypef, dapf, drop=TRUE))

# Number
print(ggplot()  +
        geom_line(data=nototal, aes(x=iteration, y=inconsistent, color=persTypef),size=1) +
        geom_point(data=nototal, aes(x=iteration, y=inconsistent, color=persTypef),size=3) +
        scale_x_continuous(breaks=c(0:numIters)) +
        labs(title=paste('Number of People with Inconsistent Schedules',sep=''),
             x = 'iSAM Iteration',
             y = 'Number of People',
             color='Person Type') +
        theme(axis.text = element_text(size=15))+
        theme(strip.text = element_text(size=15))+
        theme(plot.title = element_text(size=17))+
        theme(axis.title = element_text(size=15))+
        theme(legend.text = element_text(size=15))
)
      
print(ggplot()  +
  geom_line(data=nototal, aes(x=iteration, y=unstable, color=persTypef),size=1) +
  geom_point(data=nototal, aes(x=iteration, y=unstable, color=persTypef),size=3) +
  scale_x_continuous(breaks=c(0:numIters)) +
  labs(title=paste('Number of People with Unstable Schedules',sep=''),
       x = 'iSAM Iteration',
       y = 'Number of People',
       color='Person Type') +
    theme(axis.text = element_text(size=15))+
    theme(strip.text = element_text(size=15))+
    theme(plot.title = element_text(size=17))+
    theme(axis.title = element_text(size=15))+
    theme(legend.text = element_text(size=15))
)

print(ggplot()  +
  geom_line(data=nototal, aes(x=iteration, y=stressed, color=persTypef),size=1) +
  geom_point(data=nototal, aes(x=iteration, y=stressed, color=persTypef),size=3) +
  scale_x_continuous(breaks=c(0:numIters)) +
  labs(title=paste('Number of People with Stressed Schedules',sep=''),
       x = 'iSAM Iteration',
       y = 'Number of People',
       color='Person Type') +
    theme(axis.text = element_text(size=15))+
    theme(strip.text = element_text(size=15))+
    theme(plot.title = element_text(size=17))+
    theme(axis.title = element_text(size=15))+
    theme(legend.text = element_text(size=15))
)

# Percent
print(ggplot()  +
  geom_line(data=nototal, aes(x=iteration, y=pcinconsistent, color=persTypef),size=1) +
  geom_point(data=nototal, aes(x=iteration, y=pcinconsistent, color=persTypef),size=3) +
  scale_x_continuous(breaks=c(0:numIters)) +
  labs(title=paste('Percentage of People with Inconsistent Schedules',sep=''),
       x = 'iSAM Iteration',
       y = '% of People',
       color='Person Type') +
    theme(axis.text = element_text(size=15))+
    theme(strip.text = element_text(size=15))+
    theme(plot.title = element_text(size=17))+
    theme(axis.title = element_text(size=15))+
    theme(legend.text = element_text(size=15))
)

print(ggplot()  +
  geom_line(data=nototal, aes(x=iteration, y=pcunstable, color=persTypef),size=1) +
  geom_point(data=nototal, aes(x=iteration, y=pcunstable, color=persTypef),size=3) +
  scale_x_continuous(breaks=c(0:numIters)) +
  labs(title=paste('Percentage of People with Unstable Schedules',sep=''),
       x = 'iSAM Iteration',
       y = '% of People',
       color='Person Type') +
    theme(axis.text = element_text(size=15))+
    theme(strip.text = element_text(size=15))+
    theme(plot.title = element_text(size=17))+
    theme(axis.title = element_text(size=15))+
    theme(legend.text = element_text(size=15))
)

print(ggplot()  +
  geom_line(data=nototal, aes(x=iteration, y=pcstressed, color=persTypef),size=1) +
  geom_point(data=nototal, aes(x=iteration, y=pcstressed, color=persTypef),size=3) +
  scale_x_continuous(breaks=c(0:numIters)) +
  labs(title=paste('Percentage of People with Stressed Schedules',sep=''),
       x = 'iSAM Iteration',
       y = '% of People',
       color='Person Type') +
    theme(axis.text = element_text(size=15))+
    theme(strip.text = element_text(size=15))+
    theme(plot.title = element_text(size=17))+
    theme(axis.title = element_text(size=15))+
    theme(legend.text = element_text(size=15))
)



```

### 3 Convergence Measures for Different Person Types and DAP

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=7}

# All 3 Measures, by ptype and DAP
#-----------------------------------
for (pd in levels(perSumm$ptypeDAP)){
  
  pdn = as.numeric(pd)
  
  # Parse "level" into person type and DAP
  ptypen = floor(pdn)
  dapn   = round((pdn - ptypen)*10)
  ptype  = levels(perSumm$persTypef)[ptypen+1]
  dap    = levels(perSumm$dapf)[dapn+1]
  
  print(ggplot(data=perSumm[perSumm$ptypeDAP==pd,], aes(iteration))  +
   geom_line(aes(y=inconsistent, color="Inconsistent"),size=1) +
   geom_point(aes(y=inconsistent, color="Inconsistent"),size=3) +
   geom_line(aes(y=stressed, color="Stressed"),size=1)  +
   geom_point(aes(y=stressed, color="Stressed"),size=3) +
   geom_line(aes(y=unstable, color="Unstable"),size=1)  +
   geom_point(aes(y=unstable, color="Unstable"),size=3) +
   scale_x_continuous(breaks=c(0:numIters)) +
   labs(title=paste('',ptype,', ',dap,' Activity Pattern',sep=''),
        x = 'iSAM Iteration',
        y = 'Number of People',
        color='Schedule Status') +
          theme(axis.text = element_text(size=15))+
          theme(strip.text = element_text(size=15))+
          theme(plot.title = element_text(size=17))+
          theme(axis.title = element_text(size=15))+
          theme(legend.text = element_text(size=15))
  )
}



for (pd in levels(perSumm$ptypeDAP)){
  
  pdn = as.numeric(pd)
  
  # Parse "level" into person type and DAP
  ptypen = floor(pdn)
  dapn   = round((pdn - ptypen)*10)
  ptype  = levels(perSumm$persTypef)[ptypen+1]
  dap    = levels(perSumm$dapf)[dapn+1]

  print(ggplot(data=perSumm[perSumm$ptypeDAP==pd,], aes(iteration))  +
          geom_line(aes(y=pcinconsistent, color="Inconsistent"),size=1) +
          geom_point(aes(y=pcinconsistent, color="Inconsistent"),size=3) +
          geom_line(aes(y=pcunstable, color="Unstable"),size=1)  +
          geom_point(aes(y=pcunstable, color="Unstable"),size=3) +
          geom_line(aes(y=pcstressed, color="Stressed"),size=1)  +
          geom_point(aes(y=pcstressed, color="Stressed"),size=3) +
          scale_x_continuous(breaks=c(0:numIters)) +
          labs(title=paste('',ptype,', ',dap,' Activity Pattern',sep=''),
               x = 'iSAM Iteration',
               y = 'Percentage of People',
               color='Schedule Status') +
          theme(axis.text = element_text(size=15))+
          theme(strip.text = element_text(size=15))+
          theme(plot.title = element_text(size=17))+
          theme(axis.title = element_text(size=15))+
          theme(legend.text = element_text(size=15))
  )  
}

```




## Time Budget Measures

```{r, warning=FALSE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=10, fig.height=7}
# Time Budget
#-----------------

lastiter <- perSumm %>%
  filter(iteration == numIters)
lastiter$src <- 'Model'

survey <- read_csv("../../ExternalData/stat_travel_Budget_By_Pertype.csv")
names(survey)[names(survey)=='pertype'] <- 'persType'
names(survey)[names(survey)=='dap'] <- 'dailyActivityPattern'
names(survey)[names(survey)=='dytravtime'] <- 'avgTravelTime'
names(survey)[names(survey)=='dyacttime'] <- 'avgActTime'
survey$src <- 'Survey'
survey <- left_join(survey,lastiter[,c("persType","dailyActivityPattern","persTypef","dapf")], by=c("persType","dailyActivityPattern"))

lastitersurv <- bind_rows(lastiter,survey)
lismelt <- melt(lastitersurv[,c("persType","dailyActivityPattern","persTypef","dapf",
                                "avgTravelTime", "avgActTime","src")], 
                id.vars=c("persType","dailyActivityPattern","persTypef","dapf","src"),
                variable.name="timevar",
                value.name = "timeminutes")
lismelt <- lismelt %>%
  filter(persType >0 & !is.na(persTypef))
lismelt <- lismelt %>%
  mutate(timevarlabel = ifelse(timevar=="avgTravelTime","Avg Daily Travel Time Budget", "Avg Daily Out of Home Activity Duration"))

pertypes <- levels(lismelt$persTypef)
pertypes <- pertypes[-1]

for (pt in pertypes){
  
  print(ggplot(data=lismelt[lismelt$persTypef==pt,],aes(x=dapf, y=timeminutes, fill=src))  +
          geom_bar(stat="identity", position=position_dodge())+
          facet_grid(.~timevarlabel)+
          labs(title=paste(pt,sep=''),
               x = 'Daily Activity Pattern',
               y = 'Duration (minutes)',
               color='Source') +
          theme(axis.text = element_text(size=15))+
          theme(strip.text = element_text(size=15))+
          theme(plot.title = element_text(size=17))+
          theme(axis.title = element_text(size=15))+
          theme(legend.text = element_text(size=15))
  )
  
}


```


options(warn = oldw)